### PR TITLE
Use cncf-hosted runners

### PR DESCRIPTION
**Pull request by jeefy**

### CODE REVIEW

**Comment by jeefy** [comment]
I know merging is blocked. Please don't merge this till I debug the runner image for your usecase. :) I knew this was broken but this is the easiest way to test.

**Comment by tegioz** [comment]
Cool, no problem 👍

Would you like us to also use these runners in the other projects we maintain?

**Comment by jeefy** [comment]
Yes (once I figure out what the CI image is missing :innocent: )

**Comment by jeefy** [comment]
@tegioz Could you look into why this would be failing? https://github.com/cncf/landscape2/actions/runs/11242322179/job/31255737038 -- Is that a flake or is the runner missing some dependency? :thinking:

**Comment by tegioz** [comment]
Hi @jeefy

Those tests failed due to an internal cache that shouldn't be enabled during tests, as it could lead to race conditions like this when running tests in parallel. It's been fixed by #719.

We've never encountered this error neither when using the GitHub runners nor when running the tests locally in our machines. So it was a good catch 🙂

**Review by tegioz — APPROVED** [review]

**Comment by tegioz** [comment]
FYI @jeefy `equinix-16cpu-64gb` wasn't coming online after +15m, we've updated the build images workflow to use `equinix-4cpu-16gb` in the meantime (#720).

waiting

**Comment by jeefy** [comment]
Oof, thanks! Will look into that right now.

**Comment by jeefy** [comment]
I resolved the issue with the 16c runners BUT.... I also see the 4c runner built things in less time than the previous GitHub Action machine. So let's leave it at the 4c runner for now (unless you have objections) :)

**Comment by tegioz** [comment]
No problem, that's fine 😉

**Pull request merged**
